version = 1

[merge]
blocking_labels = ['blocked']
delete_branch_on_merge = true
method = 'squash'
require_automerge_label = false

[merge.message]
include_coauthors = true
strip_html_comments = true
title = 'pull_request_title'
