compressionLevel: mixed

enableGlobalCache: true

enableInlineHunks: true

gitHooksPath: .github/hooks

logFilters:
  # MISSING_PEER_DEPENDENCY
  - code: YN0002
    level: discard
  # NODE_GYP_INJECTED
  - code: YN0032
    level: discard

nmMode: hardlinks-global

nodeLinker: node-modules

plugins:
  - checksum: f8ce3a541a57481f6213647cfe7ac8555d87cb1fc23a73a102e64e12be07f603826d822f4d0285333400f0f15baed92510c33dcce75dde2953b2811e36efa012
    path: .yarn/plugins/@yarnpkg/plugin-git-hooks.cjs
    spec: 'https://raw.githubusercontent.com/trufflehq/yarn-plugin-git-hooks/main/bundles/%40yarnpkg/plugin-git-hooks.js'
  - checksum: b023a66bd5b071f92c561b1a3815c12f462f00ec92647f54d7ad88ae81c35cb4f25e70b6664112edcf33fef17b7b4daf55a2fd7a2abe57b7699c1805d9116f43
    path: .yarn/plugins/@yarnpkg/plugin-nolyfill.cjs
    spec: 'https://raw.githubusercontent.com/wojtekmaj/yarn-plugin-nolyfill/main/bundles/@yarnpkg/plugin-nolyfill.js'
