compressionLevel: mixed

enableGlobalCache: true

enableInlineHunks: true

nodeLinker: node-modules

logFilters:
  # MISSING_PEER_DEPENDENCY
  - code: YN0002
    level: discard
  # NODE_GYP_INJECTED
  - code: YN0032
    level: discard
