compressionLevel: mixed

enableGlobalCache: true

enableInlineHunks: true

gitHooksPath: .github/hooks

logFilters:
  # MISSING_PEER_DEPENDENCY
  - code: YN0002
    level: discard
  # NODE_GYP_INJECTED
  - code: YN0032
    level: discard

nmMode: hardlinks-global

nodeLinker: node-modules

plugins:
  - checksum: f8ce3a541a57481f6213647cfe7ac8555d87cb1fc23a73a102e64e12be07f603826d822f4d0285333400f0f15baed92510c33dcce75dde2953b2811e36efa012
    path: .yarn/plugins/@yarnpkg/plugin-git-hooks.cjs
    spec: 'https://raw.githubusercontent.com/trufflehq/yarn-plugin-git-hooks/main/bundles/%40yarnpkg/plugin-git-hooks.js'
  - checksum: 52ccdf7d7ba4e9d70ccfae8b4916c27415c4fe71d222a9e1d5ac5375707eb38f127bea3a6fd603e7f8f99d7ec5b0f67344c06f5f98cd15a5d8781ce9bb9c3f7a
    path: .yarn/plugins/@yarnpkg/plugin-nolyfill.cjs
    spec: 'https://raw.githubusercontent.com/wojtekmaj/yarn-plugin-nolyfill/v1.0.2/bundles/@yarnpkg/plugin-nolyfill.js'
