const CAMPFIRE_TALISMAN_ADEPT = {
	'LOG_2:1': 160, // dark oak wood
} as const;
const CAMPFIRE_TALISMAN_CULTIST = {
	'LOG_2:1': 160, // dark oak wood
	'LOG:1': 1_000, // spruce wood
} as const;
const CAMPFIRE_TALISMAN_SCION = {
	'LOG_2:1': 160, // dark oak wood
	'LOG:1': 1_000, // spruce wood
	LOG_2: 16_000, // acacia wood
} as const;
const CAMPFIRE_TALISMAN_GOD = {
	'LOG_2:1': 160, // dark oak wood
	'LOG:1': 1_000, // spruce wood
	LOG_2: 16_000, // acacia wood
	'LOG:3': 240_000, // jungle wood
} as const;

const _CRAFTING_RECIPES = {
	// https://hypixel-skyblock.fandom.com/wiki/Artifact_of_Power
	POWER_TALISMAN: { ROUGH_RUBY_GEM: 3_600 },
	POWER_RING: {
		ROUGH_RUBY_GEM: 48_400,
		ROUGH_JADE_GEM: 25_600,
		ROUGH_AMBER_GEM: 25_600,
		ROUGH_AMETHYST_GEM: 25_600,
		ROUGH_SAPPHIRE_GEM: 25_600,
		SLUDGE_JUICE: 320,
	},
	POWER_ARTIFACT: {
		ROUGH_RUBY_GEM: 48_400,
		ROUGH_JADE_GEM: 844_800,
		ROUGH_AMBER_GEM: 844_800,
		ROUGH_AMETHYST_GEM: 844_800,
		ROUGH_SAPPHIRE_GEM: 844_800,
		SLUDGE_JUICE: 10_560,
	},

	// https://hypixel-skyblock.fandom.com/wiki/Personal_Deletor_7000
	PERSONAL_DELETOR_4000: {
		IRON_INGOT: 18_400,
		COAL: 51_200,
		REDSTONE: 25_600,
	},
	PERSONAL_DELETOR_5000: {
		IRON_INGOT: 54_240,
		COAL: 51_200,
		REDSTONE: 25_600,
	},
	PERSONAL_DELETOR_6000: {
		IRON_INGOT: 125_920,
		COAL: 51_200,
		REDSTONE: 25_600,
	},
	PERSONAL_DELETOR_7000: {
		IRON_INGOT: 305_120,
		COAL: 51_200,
		REDSTONE: 25_600,
	},

	// https://hypixel-skyblock.fandom.com/wiki/Day_Crystal
	DAY_CRYSTAL: {
		QUARTZ: 26_240,
	},
	NIGHT_CRYSTAL: {
		QUARTZ: 26_240,
	},

	// https://hypixel-skyblock.fandom.com/wiki/Campfire_Badge
	CAMPFIRE_TALISMAN_4: CAMPFIRE_TALISMAN_ADEPT,
	CAMPFIRE_TALISMAN_5: CAMPFIRE_TALISMAN_ADEPT,
	CAMPFIRE_TALISMAN_6: CAMPFIRE_TALISMAN_ADEPT,
	CAMPFIRE_TALISMAN_7: CAMPFIRE_TALISMAN_ADEPT,
	CAMPFIRE_TALISMAN_8: CAMPFIRE_TALISMAN_CULTIST,
	CAMPFIRE_TALISMAN_9: CAMPFIRE_TALISMAN_CULTIST,
	CAMPFIRE_TALISMAN_10: CAMPFIRE_TALISMAN_CULTIST,
	CAMPFIRE_TALISMAN_11: CAMPFIRE_TALISMAN_CULTIST,
	CAMPFIRE_TALISMAN_12: CAMPFIRE_TALISMAN_CULTIST,
	CAMPFIRE_TALISMAN_13: CAMPFIRE_TALISMAN_SCION,
	CAMPFIRE_TALISMAN_14: CAMPFIRE_TALISMAN_SCION,
	CAMPFIRE_TALISMAN_15: CAMPFIRE_TALISMAN_SCION,
	CAMPFIRE_TALISMAN_16: CAMPFIRE_TALISMAN_SCION,
	CAMPFIRE_TALISMAN_17: CAMPFIRE_TALISMAN_SCION,
	CAMPFIRE_TALISMAN_18: CAMPFIRE_TALISMAN_SCION,
	CAMPFIRE_TALISMAN_19: CAMPFIRE_TALISMAN_SCION,
	CAMPFIRE_TALISMAN_20: CAMPFIRE_TALISMAN_SCION,
	CAMPFIRE_TALISMAN_21: CAMPFIRE_TALISMAN_GOD,
	CAMPFIRE_TALISMAN_22: CAMPFIRE_TALISMAN_GOD,
	CAMPFIRE_TALISMAN_23: CAMPFIRE_TALISMAN_GOD,
	CAMPFIRE_TALISMAN_24: CAMPFIRE_TALISMAN_GOD,
	CAMPFIRE_TALISMAN_25: CAMPFIRE_TALISMAN_GOD,
	CAMPFIRE_TALISMAN_26: CAMPFIRE_TALISMAN_GOD,
	CAMPFIRE_TALISMAN_27: CAMPFIRE_TALISMAN_GOD,
	CAMPFIRE_TALISMAN_28: CAMPFIRE_TALISMAN_GOD,
	CAMPFIRE_TALISMAN_29: CAMPFIRE_TALISMAN_GOD,
} as const;

/**
 * SkyBlock item crafting recipes, holds an array of { id, count } for each item
 */
export const CRAFTING_RECIPES = Object.fromEntries(
	Object.entries(_CRAFTING_RECIPES).map(([id, recipe]) => [
		id,
		Object.entries(recipe).map(([_id, count]) => ({ id: _id, count })),
	]),
);
