import { ItemId } from './itemId';

export const REFORGES = {
	"jerry's": ItemId.JerryStone,
	adept: ItemId.EndStoneShulker,
	ambered: ItemId.AmberMaterial,
	ancient: ItemId.PrecursorGear,
	aote_stone: ItemId.AoteStone,
	auspicious: ItemId.RockGemstone,
	bizarre: ItemId.EccentricPainting,
	blessed: ItemId.BlessedFruit,
	bloody: ItemId.BeatingHeart,
	bountiful: ItemId.GoldenBall,
	bulky: ItemId.BulkyStone,
	candied: ItemId.CandyCorn,
	chomp: ItemId.KuudraMandible,
	cubic: ItemId.MoltenCube,
	demonic: ItemId.HornsOfTorment,
	dirty: ItemId.DirtBottle,
	empowered: ItemId.SadanBrooch,
	fabled: ItemId.DragonClaw,
	fleet: ItemId.Diamonite,
	forceful: ItemId.AcaciaBirdhouse,
	fortified: ItemId.MeteorShard,
	fruitful: ItemId.Onyx,
	giant: ItemId.GiantTooth,
	gilded: ItemId.MidasJewel,
	glistening: ItemId.ShinyPrism,
	headstrong: ItemId.SalmonOpal,
	healthy: ItemId.VitaminDeath,
	heated: ItemId.HotStuff,
	hurtful: ItemId.MagmaUrchin,
	itchy: ItemId.Furball,
	jaded: ItemId.Jaderald,
	loving: ItemId.RedScarf,
	lucky: ItemId.LuckyDice,
	magnetic: ItemId.LapisCrystal,
	mithraic: ItemId.PureMithril,
	moil: ItemId.MoilLog,
	mythical: ItemId.ObsidianTablet,
	necrotic: ItemId.NecromancerBrooch,
	perfect: ItemId.DiamondAtom,
	pleasant: ItemId.PreciousPearl,
	precise: ItemId.OpticalLens,
	refined: ItemId.RefinedAmber,
	reinforced: ItemId.RareDiamond,
	renowned: ItemId.DragonHorn,
	ridiculous: ItemId.RedNose,
	scorching: ItemId.ScorchedBooks,
	shaded: ItemId.DarkOrb,
	sighted: ItemId.EnderMonocle,
	silky: ItemId.LuxuriousSpool,
	slender: ItemId.HazmatEnderman,
	spiked: ItemId.DragonScale,
	spiritual: ItemId.SpiritStone,
	stellar: ItemId.PetrifiedStarfall,
	stiff: ItemId.HardenedWood,
	strengthened: ItemId.SearingStone,
	submerged: ItemId.DeepSeaOrb,
	suspicious: ItemId.SuspiciousVial,
	sweet: ItemId.RockCandy,
	toil: ItemId.ToilLog,
	undead: ItemId.PremiumFlesh,
	warped: ItemId.EndstoneGeode, // sword
	// warped: ItemId.WarpedStone, // armor
	waxed: ItemId.BlazeWax,
	withered: ItemId.WitherBlood,
} as const;
