/* eslint-disable camelcase */
export const TALISMANS = new Set([
	'wedding_ring_0',
	'wedding_ring_2',
	'wedding_ring_4',
	'wedding_ring_7',
	'wedding_ring_9',

	'campfire_talisman_1',
	'campfire_talisman_4',
	'campfire_talisman_8',
	'campfire_talisman_13',
	'campfire_talisman_21',

	// 'farming_talisman',
	'vaccine_talisman',
	'wood_talisman',
	// 'skeleton_talisman',
	'coin_talisman',
	// 'magnetic_talisman',
	// 'gravity_talisman',
	// 'village_talisman',
	// 'mine_talisman',
	// 'night_vision_charm',
	// 'lava_talisman',
	// 'scavenger_talisman',
	// 'fire_talisman',
	// 'piggy_bank',
	// 'cracked_piggy_bank',
	// 'broken_piggy_bank',
	// 'pigs_foot',
	// 'wolf_paw',
	// 'frozen_chicken',
	// 'fish_affinity_talisman',
	// 'farmer_orb',
	// 'haste_ring',
	// 'experience_artifact',
	// 'new_year_cake_bag',
	'day_crystal',
	'night_crystal',
	// 'feather_talisman',
	// 'feather_ring',
	// 'feather_artifact',
	// 'potion_affinity_talisman',
	// 'ring_potion_affinity',
	// 'artifact_potion_affinity',
	// 'healing_talisman',
	// 'healing_ring',
	// 'candy_talisman',
	// 'candy_ring',
	// 'candy_artifact',
	'melody_hair',
	'sea_creature_talisman',
	// 'sea_creature_ring',
	// 'sea_creature_artifact',
	// 'intimidation_talisman',
	// 'intimidation_ring',
	// 'intimidation_artifact',
	// 'wolf_talisman',
	// 'wolf_ring',
	// 'bat_talisman',
	// 'bat_ring',
	// 'bat_artifact',
	// 'devour_ring',
	// 'zombie_talisman',
	// 'zombie_ring',
	// 'zombie_artifact',
	// 'spider_talisman',
	// 'spider_ring',
	// 'spider_artifact',
	// 'ender_artifact',
	// 'tarantula_talisman',
	// 'survivor_cube',
	// 'wither_artifact',
	// 'red_claw_talisman',
	// 'red_claw_ring',
	// 'red_claw_artifact',
	// 'bait_ring',
	// 'shady_ring',
	// 'crooked_artifact',
	// 'seal_of_the_family',
	// 'hunter_talisman',
	// 'hunter_ring',
	// 'party_hat_crab',
	// 'potato_talisman',
	'emerald_ring',
	'personal_compactor_4000',
	'personal_compactor_5000',
	'personal_compactor_6000',
	'personal_compactor_7000',
	'personal_deletor_4000',
	'personal_deletor_5000',
	'personal_deletor_6000',
	'personal_deletor_7000',
	'speed_talisman',
	'speed_ring',
	'speed_artifact',
	'cat_talisman',
	'lynx_talisman',
	'cheetah_talisman',
	'scarf_studies',
	'scarf_thesis',
	'scarf_grimoire',
	'treasure_talisman',
	'treasure_ring',
	'treasure_artifact',
	'mineral_talisman',
	'beastmaster_crest_common',
	'beastmaster_crest_uncommon',
	'beastmaster_crest_rare',
	'beastmaster_crest_epic',
	'beastmaster_crest_legendary',
	'raggedy_shark_tooth_necklace',
	'dull_shark_tooth_necklace',
	'honed_shark_tooth_necklace',
	'sharp_shark_tooth_necklace',
	'razor_sharp_shark_tooth_necklace',
	'hegemony_artifact',
	'bits_talisman',
	'bat_person_talisman',
	'bat_person_ring',
	'bat_person_artifact',
	'candy_relic',
	// 'lucky_hoof',
	// 'eternal_hoof',
	'wither_relic',
	'catacombs_expert_ring',
	'auto_recombobulator',
	'jerry_talisman_green',
	'jerry_talisman_blue',
	'jerry_talisman_purple',
	'jerry_talisman_golden',
	'king_talisman',
	'titanium_talisman',
	'titanium_ring',
	'titanium_artifact',
	'titanium_relic',
	'reaper_orb',
	'dante_talisman',
	'spiked_atrocity',
	'blood_god_crest',
	'master_skull_tier_1',
	'master_skull_tier_2',
	'master_skull_tier_3',
	'master_skull_tier_4',
	'master_skull_tier_5',
	'master_skull_tier_6',
	'master_skull_tier_7',
	'soulflow_pile',
	'soulflow_battery',
	'soulflow_supercell',
	'pocket_espresso_machine',
	'handy_blood_chalice',
	'ender_relic',
	'jungle_amulet',
	'power_talisman',
	'power_ring',
	'power_artifact',
	'nether_artifact',
	'bingo_talisman',
	'bingo_ring',
]);
