'use strict';

module.exports = {
	EMBED_MAX_CHARS: 6_000,
	EMBED_MAX_FIELDS: 25,
	EMBED_FIELD_MAX_CHARS: 1_024,
	EMBED_DESCRIPTION_MAX_CHARS: 2_048,
	EMBEDS_MAX_AMOUNT: 10,
	MESSAGE_MAX_CHARS: 2_000,
	NICKNAME_MAX_CHARS: 32,
};
