export const enum ItemCategory {
	Accessory = 'ACCESSORY',
	Arrow = 'ARROW',
	ArrowPoison = 'ARROW_POISON',
	Axe = 'AXE',
	Bait = 'BAIT',
	Belt = 'BELT',
	Boots = 'BOOTS',
	Bow = 'BOW',
	Bracelet = 'BRACELET',
	Chestplate = 'CHESTPLATE',
	Cloak = 'CLOAK',
	Cosmetic = 'COSMETIC',
	Deployable = 'DEPLOYABLE',
	Drill = 'DRILL',
	DungeonPass = 'DUNGEON_PASS',
	FishingRod = 'FISHING_ROD',
	FishingWeapon = 'FISHING_WEAPON',
	Gauntlet = 'GAUNTLET',
	Gloves = 'GLOVES',
	Helmet = 'HELMET',
	Hoe = 'HOE',
	Leggings = 'LEGGINGS',
	Longsword = 'LONGSWORD',
	Necklace = 'NECKLACE',
	None = 'NONE',
	PetItem = 'PET_ITEM',
	Pickaxe = 'PICKAXE',
	ReforgeStone = 'REFORGE_STONE',
	Shears = 'SHEARS',
	Spade = 'SPADE',
	Sword = 'SWORD',
	TravelScroll = 'TRAVEL_SCROLL',
	Wand = 'WAND',
}

export const ALLOWED_RECOMB_CATEGORIES = new Set([
	ItemCategory.Accessory,
	ItemCategory.Belt,
	ItemCategory.Bracelet,
	ItemCategory.Cloak,
	ItemCategory.Gloves,
	ItemCategory.Necklace,
] as const);
