name: Cleanup pnpm caches

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Cleanup caches
        uses: ./.github/actions/delete-actions-cache
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          filter: 'pnpm- ${{ runner.os }}-pnpm-'
